# Generated by Django 3.2 on 2022-02-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
