# Generated by Django 3.2 on 2022-02-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='category',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subject',
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='topic', max_length=50),
            preserve_default=False,
        ),
    ]
