# Generated by Django 3.2 on 2022-01-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
