# Generated by Django 3.2 on 2022-01-31 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_productreview_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='category',
        ),
    ]
