# Generated by Django 3.2 on 2022-02-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_productreview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='title',
            field=models.TextField(default='Review Title', max_length=30),
        ),
    ]
