# Generated by Django 3.2 on 2022-02-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_productreview_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-date']},
        ),
    ]
